
import React from 'react'
import Hero from '@/components/Hero'
import homeSrc from '@/../public/01.jpg'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function Page() {
  return (
    <Hero imgurl={homeSrc} alt="home image"  content="Hero标题内容"/>
  );
}


