
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";



const Robotofont = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["vietnamese"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Robotofont.variable} >
      
        {children}
      </body>
    </html>
  );
}
