import React from 'react'
import ScaleSrc from "@/../public/03.jpg"
import Hero from '@/components/Hero'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Scale page',
  description: 'Generated by create next app',
}
export default function Page() {
  return (
    
    <Hero imgurl={ScaleSrc} alt="Scale page image"  content="Scale page content"/>
  )
}
