import React from 'react'
import Hero from '@/components/Hero'
import performanceSrc from '@/../public/04.jpg'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Performance page',
  description: 'Generated by create next app',
}
export default function Page() {
  return (
    
    <Hero imgurl={performanceSrc} alt="Performance page image"  content="Performance page内容"/>
  )
}