import React from 'react'
import Hero from '@/components/Hero'
import reliabilitySrc from '@/../public/02.jpg' 
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Reliability page',
  description: 'Generated by create next app',
}
export default function Page() {
  return (
    
    <Hero imgurl={reliabilitySrc} alt="Reliability page image"  content="Reliability page Generated by create next app"/>
  )
}